### ISSUE TITLE
Does this still works on the latest version?

### ISSUE THREAD

**Issue by LunarstarFurry** [sam-k0/LC_Highlights#2]
Have this installed now but it doesn't seems to do anything at all? Didn't have the popup from Nvidia mention about the high lights being enabled either

**Comment by sam-k0** [comment]
I haven't updated or tried it for the newer versions of the game as I am no longer using a Nvidia GPU nor Windows. 

- Do you have the Geforce experience driver installed? 

- Do you use the prebuilt version from thunderstore/github release or a local build?

- Is there any error log when starting the game with the mod?

My guesses are the mod doesn't work because game addresses have been changed or because Geforce experience had an update, breaking the SDK that the mod is using.

**Comment by LunarstarFurry** [comment]
1: Yes, it works just fine with Fortnite

2: Thunderstore Build

3: Here's the log

```
[Info   :   BepInEx] Loading [GeForce Highlights 2024.3.23]
[Error  : Unity Log] DllNotFoundException: HighlightsPlugin64 assembly:<unknown assembly> type:<unknown type> member:(null)
Stack trace:
NVIDIA.Highlights.CreateHighlightsSDK (System.String AppName, NVIDIA.Highlights+HighlightScope[] RequiredScopes) (at <6ee17fa3885a4f0186fc1b9c8f27e77a>:0)
LC_Highlights.Plugin.Awake () (at <6ee17fa3885a4f0186fc1b9c8f27e77a>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()
```

**Comment by sam-k0** [comment]
The `DllNotFoundException` suggests that the `GfeSDK.dll and HighlightsPlugin64.dll` couldn't be found.
This is an issue when installing the mod from Thunderstore, as the mod manager does not move the two dlls to their correct location.
Make sure you move them to `Lethal Company\Lethal Company_Data\Plugins\x86_64`.
You can download them from the [release](https://github.com/sam-k0/LC_Highlights/releases/tag/2024.03.22) here.
You can find your game install directory by going to the game in your steam library and clicking the settings button for `Lethal Company -> Manage...->Browse local files`

**Comment by LunarstarFurry** [comment]
Fixed Thankyou! < 3
